#!/bin/bash
. /lib/lsb/init-functions
source ~jimmy/.rvm/scripts/rvm
EXECUTABLE=`which config_writer`
PID_NAME=ky_config_writer

start() {
        echo "Starting config_writer"
	source ~jimmy/.rvm/scripts/rvm
        start-stop-daemon --make-pidfile --start --oknodo --background --pidfile "/var/run/"$PID_NAME".pid" --chuid jimmy --chdir ~jimmy/ --startas $EXECUTABLE -- -l config_writer.log /dev/ttyO1
}

stop() {
        echo "Stopping config_writer"
	start-stop-daemon --stop --quiet --oknodo --pidfile "/var/run/"$PID_NAME".pid"
}

restart() {
        stop
        start
}

case "$1" in 
start)
        start
;;
stop)
        stop
;;
restart)
        restart
;;
status)
	status_of_proc -p "/var/run/"$PID_NAME".pid" $EXECUTABLE config_writer
;;

*)
	echo $"Usage: $0 {start|stop|restart|status}"
	exit 1
esac
exit 0 
